### ISSUE TITLE
一直显示打卡失败啊（本科生）

### ISSUE THREAD

**Issue by akirakusen** [Xiderowg/HHUHealthCheckinGUI#1]
原因为：未知原因

**Comment by Xiderowg** [comment]
已于https://github.com/Xiderowg/HHUHealthCheckinGUI/commit/dadc44a10e3b866bc09e3ebf3b98c9ae4dbf0f84 中修复。
现在研究生已经不要求打卡了，本科生还强制么？

**Comment by akirakusen** [comment]
目前是强制的，好像在一个月前打卡界面有了变化，所以出了问题



发送自我的盖乐世



-------- 原始信息 --------
发件人： Xiderowg <notifications@github.com>
日期: 2020/11/25 12:04 (GMT+08:00)
收件人： Xiderowg/HHUHealthCheckinGUI <HHUHealthCheckinGUI@noreply.github.com>
抄送： Ricky Chu <qs4869@outlook.com>, Author <author@noreply.github.com>
主题： Re: [Xiderowg/HHUHealthCheckinGUI] 一直显示打卡失败啊（本科生） (#1)


已于dadc44a10e3b866bc09e3ebf3b98c9ae4dbf0f84中修复。
现在研究生已经不要求打卡了，本科生还强制么？

―

**Comment by akirakusen** [comment]
可否增加一个release呢?

**Comment by Xiderowg** [comment]
> 可否增加一个release呢?

已增，参见https://github.com/Xiderowg/HHUHealthCheckinGUI/releases

**Comment by akirakusen** [comment]
好的感谢
